
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-back-communication-deployment
  labels:
    app: api-back-communication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-back-communication
  template:
    metadata:
      labels:
        app: api-back-communication
    spec:
      containers:
      - name: api-back-communication-deployment
        image: mycluster.azurecr.io/back-models
        ports:
        - containerPort: 3004

---
kind: Service
apiVersion: v1
metadata:
  name: api-back-communication-service
spec:
  type: LoadBalancer
  selector:
    app: api-back-communication
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3004
    